version: '3'

services:
  external:
    container_name: svelteytdl
    image: svelteytdl
    build:
      context: .
      dockerfile: Dockerfile
    user: 'node'
    environment:
      - NODE_ENV=production
      - TZ=Europe/Berlin
    # For now we skip the .env file
    #env_file:
    #  - .env
    restart: unless-stopped
    ports:
      - 5050:3000
